name: Run Tests
on:
  pull_request:
  push:
  workflow_dispatch:
jobs:
  tests:
    runs-on: windows-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.9'
        - name: Install deps
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install -r requirements-test.txt
        - name: Run unittest
          run: |
            coverage run -m unittest
            coverage xml
        - name: Upload codecov
          uses: codecov/codecov-action@v1
          with:
            verbose: true
            flags: unittests,pull_request
            file: ./coverage.xml
            name: pull_request
            fail_ci_if_error: true